# See https://pre-commit.com for more information
ci:
  autofix_prs: false
  autoupdate_schedule: quarterly
  autoupdate_branch: pre-commit-autoupdate
  # Skip steps that won't run on pre-commit CI for various reasons,
  # mostly because they rely on local things.
  skip: [ ]

# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      # Prevent committing .rej files
      - id: forbidden-files
        name: forbidden files
        entry: found Copier update rejection files; review them and remove them
        language: fail
        files: "\\.rej$"
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.8'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format
  - repo: https://github.com/pdm-project/pdm
    rev: 2.17.0
    hooks:
      # Check that the lock file is up to date.
      - id: pdm-lock-check
        args: [ --dev, --group, ":all" ]
      # Put a requirements.txt file in the repo too
      - id: pdm-export
        args: ['--prod', '-o', 'requirements.txt', '--without-hashes']
      - id: pdm-sync
