# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Thank you also https://browniebroke.com/blog/specify-docs-dependency-groups-with-poetry-and-read-the-docs/

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install pdm
    post_install:
      # RtD seems to be not happy with poetry installs,
      # hence use pip directly instead.
      - pdm export -f requirements --output requirements.txt --with docs
      - python -m pip install -r requirements.txt
      - python -m pip list

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true
